window.esdocSearchIndex = [
  [
    "jimple/src/proxy.js~jimple",
    "variable/index.html#static-variable-Jimple",
    "<span>Jimple</span> <span class=\"search-result-import-path\">jimple/src/proxy.js</span>",
    "variable"
  ],
  [
    "jimple~jimple",
    "class/src/index.js~Jimple.html",
    "<span>Jimple</span> <span class=\"search-result-import-path\">jimple</span>",
    "class"
  ],
  [
    "jimple/src/proxy.js~jimpleproxy",
    "class/src/proxy.js~JimpleProxy.html",
    "<span>JimpleProxy</span> <span class=\"search-result-import-path\">jimple/src/proxy.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber5",
    "Jimple",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber19",
    "Jimple .define",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber22",
    "Jimple .define should define service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber38",
    "Jimple .define should not tag same callable twice",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber20",
    "Jimple .define should return jimple instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber24",
    "Jimple .define should store callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber30",
    "Jimple .define should store value as callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber36",
    "Jimple .define should tag callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber138",
    "Jimple .extend",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber141",
    "Jimple .extend should extend existing service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber150",
    "Jimple .extend should receive base service instance as first argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber161",
    "Jimple .extend should receive jimple instance as second argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber170",
    "Jimple .extend should refuse to extend an already fetched service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber176",
    "Jimple .extend should refuse to extend an already used factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber139",
    "Jimple .extend should return jimple instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber96",
    "Jimple .factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber117",
    "Jimple .factory factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber118",
    "Jimple .factory factory should not share service instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber128",
    "Jimple .factory factory should receive jimple instance as an argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber108",
    "Jimple .factory should delete shared instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber97",
    "Jimple .factory should return jimple instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber99",
    "Jimple .factory should wrap callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber210",
    "Jimple .protect",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber211",
    "Jimple .protect should wrap callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber239",
    "Jimple .proxify",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber351",
    "Jimple .proxify .factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber352",
    "Jimple .proxify .factory factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber353",
    "Jimple .proxify .factory factory should receive jimple proxy instance as an argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber336",
    "Jimple .proxify .share",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber337",
    "Jimple .proxify .share factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber338",
    "Jimple .proxify .share factory should receive jimple proxy instance as an argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber251",
    "Jimple .proxify should be extensible",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber253",
    "Jimple .proxify should be idempotent",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber249",
    "Jimple .proxify should return a proxified instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber258",
    "Jimple .proxify traps",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber326",
    "Jimple .proxify traps .delete",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber327",
    "Jimple .proxify traps .delete should prevent deletion",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber259",
    "Jimple .proxify traps .get",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber278",
    "Jimple .proxify traps .get should execute factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber269",
    "Jimple .proxify traps .get should fetch service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber260",
    "Jimple .proxify traps .get should not override native methods",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber308",
    "Jimple .proxify traps .has",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber317",
    "Jimple .proxify traps .has should check if factory exists",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber309",
    "Jimple .proxify traps .has should check if service exists",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber290",
    "Jimple .proxify traps .set",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber298",
    "Jimple .proxify traps .set should define a shared service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber291",
    "Jimple .proxify traps .set should refuse to override native methods",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber219",
    "Jimple .raw",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber220",
    "Jimple .raw should return raw callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber226",
    "Jimple .raw should return raw callable for value",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber41",
    "Jimple .share",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber62",
    "Jimple .share factory",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber73",
    "Jimple .share factory should receive jimple instance as an argument",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber81",
    "Jimple .share factory should reset when service change",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber63",
    "Jimple .share factory should share service instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber53",
    "Jimple .share should overwrite existing service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber42",
    "Jimple .share should return jimple instance",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber44",
    "Jimple .share should wrap callable",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber229",
    "Jimple .tagged",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber230",
    "Jimple .tagged should return tagged service names",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber183",
    "Jimple .use",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber186",
    "Jimple .use should inject given service",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber195",
    "Jimple .use should inject given services",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber184",
    "Jimple .use should inject jimple",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber12",
    "Jimple should be empty",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber14",
    "Jimple should be frozen",
    "test"
  ],
  [
    "",
    "test-file/tests/jimple.js.html#lineNumber10",
    "Jimple should instanciate",
    "test"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~jimple#constructor",
    "class/src/index.js~Jimple.html#instance-constructor-constructor",
    "src/index.js~Jimple#constructor",
    "method"
  ],
  [
    "src/index.js~jimple#define",
    "class/src/index.js~Jimple.html#instance-method-define",
    "src/index.js~Jimple#define",
    "method"
  ],
  [
    "src/index.js~jimple#exists",
    "class/src/index.js~Jimple.html#instance-method-exists",
    "src/index.js~Jimple#exists",
    "method"
  ],
  [
    "src/index.js~jimple#extend",
    "class/src/index.js~Jimple.html#instance-method-extend",
    "src/index.js~Jimple#extend",
    "method"
  ],
  [
    "src/index.js~jimple#factory",
    "class/src/index.js~Jimple.html#instance-method-factory",
    "src/index.js~Jimple#factory",
    "method"
  ],
  [
    "src/index.js~jimple#frozen",
    "class/src/index.js~Jimple.html#instance-member-frozen",
    "src/index.js~Jimple#frozen",
    "member"
  ],
  [
    "src/index.js~jimple#get",
    "class/src/index.js~Jimple.html#instance-method-get",
    "src/index.js~Jimple#get",
    "method"
  ],
  [
    "src/index.js~jimple#gettagged",
    "class/src/index.js~Jimple.html#instance-method-getTagged",
    "src/index.js~Jimple#getTagged",
    "method"
  ],
  [
    "src/index.js~jimple#keys",
    "class/src/index.js~Jimple.html#instance-method-keys",
    "src/index.js~Jimple#keys",
    "method"
  ],
  [
    "src/index.js~jimple#protect",
    "class/src/index.js~Jimple.html#instance-method-protect",
    "src/index.js~Jimple#protect",
    "method"
  ],
  [
    "src/index.js~jimple#proxified",
    "class/src/index.js~Jimple.html#instance-member-proxified",
    "src/index.js~Jimple#proxified",
    "member"
  ],
  [
    "src/index.js~jimple#proxify",
    "class/src/index.js~Jimple.html#instance-method-proxify",
    "src/index.js~Jimple#proxify",
    "method"
  ],
  [
    "src/index.js~jimple#raw",
    "class/src/index.js~Jimple.html#instance-method-raw",
    "src/index.js~Jimple#raw",
    "method"
  ],
  [
    "src/index.js~jimple#share",
    "class/src/index.js~Jimple.html#instance-method-share",
    "src/index.js~Jimple#share",
    "method"
  ],
  [
    "src/index.js~jimple#shared",
    "class/src/index.js~Jimple.html#instance-member-shared",
    "src/index.js~Jimple#shared",
    "member"
  ],
  [
    "src/index.js~jimple#tagged",
    "class/src/index.js~Jimple.html#instance-method-tagged",
    "src/index.js~Jimple#tagged",
    "method"
  ],
  [
    "src/index.js~jimple#tagmap",
    "class/src/index.js~Jimple.html#instance-member-tagmap",
    "src/index.js~Jimple#tagmap",
    "member"
  ],
  [
    "src/index.js~jimple#use",
    "class/src/index.js~Jimple.html#instance-method-use",
    "src/index.js~Jimple#use",
    "method"
  ],
  [
    "src/index.js~jimple#values",
    "class/src/index.js~Jimple.html#instance-member-values",
    "src/index.js~Jimple#values",
    "member"
  ],
  [
    "src/proxy.js",
    "file/src/proxy.js.html",
    "src/proxy.js",
    "file"
  ],
  [
    "src/proxy.js~jimpleproxy#constructor",
    "class/src/proxy.js~JimpleProxy.html#instance-constructor-constructor",
    "src/proxy.js~JimpleProxy#constructor",
    "method"
  ],
  [
    "tests/jimple.js",
    "test-file/tests/jimple.js.html",
    "tests/jimple.js",
    "testFile"
  ]
]